
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Force HTTPS
[[redirects]]
  from = "http://alfaisalgroup.com.sa/*"
  to = "https://alfaisalgroup.com.sa/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.alfaisalgroup.com.sa/*"
  to = "https://alfaisalgroup.com.sa/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.alfaisalgroup.com.sa/*"
  to = "https://alfaisalgroup.com.sa/:splat"
  status = 301
  force = true

# Landing page handling
[[redirects]]
  from = "/landing"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/landing/*"
  to = "/index.html"
  status = 200

# Project details pages
[[redirects]]
  from = "/project/*"
  to = "/index.html"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "upgrade-insecure-requests; default-src 'self' https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' data: https:; connect-src 'self' https:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cache-Control = '''
    public,
    max-age=31536000,
    immutable'''

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/lovable-uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
